FROM python:3.14-slim

WORKDIR /app

COPY requirements.txt /app
RUN pip install -r requirements.txt

RUN apt-get update && apt-get install -y \
    git \
    && rm -rf /var/lib/apt/lists/*

COPY . /app

EXPOSE 5000

CMD ["flask", "run", "--host=0.0.0.0", "--debug"]