services:
  frontend:
    build: 
      context: ../frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
  
  backend:
    build: 
      context: ../backend
      dockerfile: Dockerfile.dev
    ports:
      - "5001:5000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - DATABASE_URL=mysql+pymysql://root:secret@db/db
    volumes:
      - ..:/workspaces

  db:
    image: mysql:9.6.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - mysql_data_dev:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    ports:
      - "3306:3306"

volumes:
  mysql_data_dev: